name: rock_n_weather
description: Rock'n'Weather
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  dio: ^5.4.1
  injector: ^3.0.0
  flutter_riverpod: ^2.4.10
  grouped_list: ^4.0.0

  mockito: ^5.4.4
  build_runner: ^2.4.8
  network_image_mock: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true